name: git push into another repo to deploy to vercel

on:
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # 템플릿 구문 처리 위해 필요
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      # Runs a set of commands using the runners shell
      - name: creates output
        run: sh ./build.sh

      - name: push to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PHJOON_GITHUB_REPO_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: PHJoon
          destination-repository-name: abcdedu-frontend
          user-email: ${{ secrets.PHJOON_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: develop

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
